#!/usr/bin/env python3
"""Constants for PR168-GFP2 provenance reopening artifacts."""

from __future__ import annotations

from pathlib import Path


PR_ID = "PR168-GFP2"
REPORT_VERSION = "pr168_gfp2_v1"
CREATED_BY_TOOL = "tools/build_pr168_gfp2_full_universe_formula_data_provenance_reopen.py"
GENERATED_DIR = Path("docs/master_plan/generated")
SHARD_DIR = GENERATED_DIR / "pr168_gfp2_shards"
SHARD_SIZE = 1000

BASELINE_COUNTS = {
    "historical_master_qku_count": 9360,
    "candidate_packet_v1_count": 6502,
    "atomic_rows_bridge_count": 4183,
    "formula_assignment_count": 20387,
    "selected_formula_count": 35,
}

AUTHORITY_CLASS = (
    "PROVENANCE_GATED_FORMULA_DATA_AUDIT_NO_LIVE_NO_PROFIT_NO_SOURCE_TRUTH_AUTHORITY"
)
DOWNGRADED_AUTHORITY_CLASS = "PROVENANCE_DOWNGRADED_PRIOR_RESULT"
CONNECTED = "CONNECTED_TO_DECLARED_CONSUMER"
TERMINAL_CONNECTED = "TERMINAL_WITH_EXACT_REASON_AND_GOVERNANCE_CONSUMER"

NO_AUTHORITY_FLAGS = {
    "manual_edit_allowed_flag": False,
    "qku_sha_or_atomicrows_hash_authority_flag": False,
    "qtt_sha_or_atomicrows_hash_authority_flag": False,
    "live_authority_created_flag": False,
    "order_authority_created_flag": False,
    "source_truth_acceptance_created_flag": False,
    "connector_semantic_binding_created_flag": False,
    "private_state_accessed_flag": False,
    "cash_accessed_flag": False,
    "quantum_backend_execution_flag": False,
    "quantum_advantage_claim_flag": False,
    "profit_evidence_created_flag": False,
    "profit_guarantee_created_flag": False,
}

ACCEPTED_REAL_DATA_TIERS = frozenset(
    {
        "ACCEPTED_REAL_MARKET_DATA",
        "ACCEPTED_REAL_HISTORICAL_REPLAY_DATA",
        "ACCEPTED_REAL_CURRENT_MARKET_SNAPSHOT",
        "ACCEPTED_REAL_ORDERBOOK_DATA",
        "ACCEPTED_REAL_TRADE_FILL_DATA",
        "ACCEPTED_REAL_RESOLUTION_SETTLEMENT_DATA",
        "ACCEPTED_REAL_FEE_COST_DATA",
        "ACCEPTED_REAL_LATENCY_DATA",
    }
)

EVIDENCE_TIERS = (
    "ACCEPTED_REAL_MARKET_DATA",
    "ACCEPTED_REAL_HISTORICAL_REPLAY_DATA",
    "ACCEPTED_REAL_CURRENT_MARKET_SNAPSHOT",
    "ACCEPTED_REAL_ORDERBOOK_DATA",
    "ACCEPTED_REAL_TRADE_FILL_DATA",
    "ACCEPTED_REAL_RESOLUTION_SETTLEMENT_DATA",
    "ACCEPTED_REAL_FEE_COST_DATA",
    "ACCEPTED_REAL_LATENCY_DATA",
    "OFFICIAL_SOURCE_CANDIDATE",
    "NON_OFFICIAL_SOURCE_CANDIDATE",
    "WEB_RESEARCH_CANDIDATE",
    "SOCIAL_RESEARCH_CANDIDATE",
    "OWNER_SUBMITTED_CANDIDATE",
    "INSTITUTIONAL_RESEARCH_CANDIDATE",
    "REPO_LOCAL_GENERATED_EVIDENCE",
    "PROXY_DEFAULT",
    "SYNTHETIC_FIXTURE",
    "GAP_ROUTED",
    "UNKNOWN_OR_UNVERIFIED",
    "SUPERSEDED_HISTORICAL_EVIDENCE_ONLY",
    "PROVENANCE_DOWNGRADED_PRIOR_RESULT",
)

REAL_PROOF_COMPONENTS = (
    "formula_expression_ref",
    "accepted_source_evidence_ref",
    "market_data_asof_ref",
    "replay_or_current_data_lock_ref",
    "historical_or_current_orderbook_ref",
    "trade_or_fill_data_ref",
    "resolution_or_settlement_ref",
    "fee_model_ref",
    "slippage_model_ref",
    "fill_probability_model_ref",
    "latency_model_ref",
    "capacity_depth_model_ref",
    "computation_receipt_ref",
    "numeric_evidence_values",
    "data_provenance_receipt_ref",
)

REQUIRED_UPSTREAM_ARTIFACTS = (
    "docs/master_plan/QTT_MasterPlan_Current.md",
    "docs/roadmap/QTT_PRs_Roadmap_Index_v1_0.json",
    "docs/roadmap/QTT_PR_Blueprints_Index_PR83_to_PR224_v1_0.json",
    "docs/master_plan/generated/PR135RouteTriage.report.json",
    "docs/master_plan/generated/PR135MasterPlanSectionCrosswalk.report.json",
    "docs/master_plan/generated/PR135MarketSpecificSectionIndex.report.json",
    "docs/master_plan/generated/PR135CommandActionMatrix.report.json",
    "docs/master_plan/generated/PR165_D2_AgentRosterDiscoveryAudit.report.json",
    "docs/master_plan/generated/PR165_D2_AgentDutySourceCrosswalk.report.json",
    "docs/master_plan/generated/PR168_GFP_QKUBaselineCountReconcile.report.json",
    "docs/master_plan/generated/PR168_GFP_Historical9360VsCurrent6502Reconcile.report.json",
    "docs/master_plan/generated/PR168_GFP_SelectedFormulaExpressionRegistry.report.json",
    "docs/master_plan/generated/PR168_GFP_FormulaAssignmentMatrix.report.json",
    "docs/master_plan/generated/PR168_GFP_AuthoritativeTruthOverlay.report.json",
    "docs/master_plan/generated/PR168_RP_FinalSummary.report.json",
    "docs/master_plan/generated/PR168_RP_ComputedPositiveEdgeCandidates.report.json",
    "docs/master_plan/generated/PR168_RP_ComputedNegativeEdgeCandidates.report.json",
    "docs/master_plan/generated/PR168_RP_ComputedNeutralOrZeroEdgeCandidates.report.json",
    "docs/master_plan/generated/PR168_RP_PreTradeSimulationCandidates.report.json",
    "docs/master_plan/generated/PR168_RP_NoTradeCandidateComparison.report.json",
    "docs/master_plan/generated/PR168_RP_TrueNegativeAfterRecoveryExhaustion.report.json",
    "docs/master_plan/generated/PR168_RANK_FinalSummary.report.json",
    "docs/master_plan/generated/PR168_RANK_NoTradeDominanceResults.report.json",
    "docs/master_plan/source_evidence/QTT_OWNER_SOURCE_EVIDENCE_DEFINITIONS_PACKET.md",
    "docs/master_plan/source_evidence/generated/AcceptedSourceEvidenceLedger.report.json",
)

REQUIRED_REPORTS = (
    "PR168_GFP2_FullUniverseInputDiscovery.report.json",
    "PR168_GFP2_9360QKUUniverseReconciliation.report.json",
    "PR168_GFP2_6502CandidatePacketReconciliation.report.json",
    "PR168_GFP2_AtomicRows4183Bridge.report.json",
    "PR168_GFP2_FormulaAssignment20387Audit.report.json",
    "PR168_GFP2_Selected35FormulaProvenance.report.json",
    "PR168_GFP2_UnselectedQKUReopenLedger.report.json",
    "PR168_GFP2_SelectionDecisionProvenanceLedger.report.json",
    "PR168_GFP2_ComputabilityDowngradeLedger.report.json",
    "PR168_GFP2_AllQKUComputabilityClassificationLedger.report.json",
    "PR168_GFP2_DataTierClassification.report.json",
    "PR168_GFP2_RealMarketDataUsageAudit.report.json",
    "PR168_GFP2_AcceptedRealDataDiscovery.report.json",
    "PR168_GFP2_AcceptedRealDataComputationEligibility.report.json",
    "PR168_GFP2_RealDataFormulaExecutionLedger.report.json",
    "PR168_GFP2_RealPositiveNegativeProofLedger.report.json",
    "PR168_GFP2_ZeroPositiveNotFinalTruthAudit.report.json",
    "PR168_GFP2_RealDataMissingProofComponentQueue.report.json",
    "PR168_GFP2_RealDataAsOfAndReplayLockAudit.report.json",
    "PR168_GFP2_RealDataSampleSizeAndCoverageAudit.report.json",
    "PR168_GFP2_NumericEvidenceProvenanceMatrix.report.json",
    "PR168_GFP2_ExternalCandidateSourceAcquisitionLedger.report.json",
    "PR168_GFP2_NonOfficialCandidateSourceLane.report.json",
    "PR168_GFP2_SourceConflictAndStalenessAudit.report.json",
    "PR168_GFP2_VenueDataBindingCandidateSurface.report.json",
    "PR168_GFP2_ProxySyntheticGeneratedEvidenceAudit.report.json",
    "PR168_GFP2_PriorPositiveNegativeAuthorityDowngradeLedger.report.json",
    "PR168_GFP2_PriorResultSupersessionLedger.report.json",
    "PR168_GFP2_FakePositiveCorrectionQueue.report.json",
    "PR168_GFP2_FakeNegativeReopenQueue.report.json",
    "PR168_GFP2_FakeNeutralZeroNoTradeReopenQueue.report.json",
    "PR168_GFP2_MetadataNonComputableReopenQueue.report.json",
    "PR168_GFP2_ChampionAuthorityStripLedger.report.json",
    "PR168_GFP2_RealMarketRecomputeRequiredLedger.report.json",
    "PR168_GFP2_ResultAuthorityTransitionAudit.report.json",
    "PR168_GFP2_PriorResultAgentBeliefRoutingLedger.report.json",
    "PR168_GFP2_GapRoutedUniverseRepairQueue.report.json",
    "PR168_GFP2_FormulaInputMapRepairQueue.report.json",
    "PR168_GFP2_MarketVenuePayoffDataBindingQueue.report.json",
    "PR168_GFP2_OrderbookTradeResolutionDataBindingQueue.report.json",
    "PR168_GFP2_FeeSlippageFillLatencyTCADataBindingQueue.report.json",
    "PR168_GFP2_CurrentMarketDataCandidateBindingQueue.report.json",
    "PR168_GFP2_HistoricalReplayDataCandidateBindingQueue.report.json",
    "PR168_GFP2_AlphaCaptureMechanismRegistry.report.json",
    "PR168_GFP2_CandidateStackSearchSpaceManifest.report.json",
    "PR168_GFP2_TradeOrderSimulationStackSpecQueue.report.json",
    "PR168_GFP2_ExecutionAdjustedExpectedValueFormulaRegistry.report.json",
    "PR168_GFP2_OrderPolicyAlternativeSeed.report.json",
    "PR168_GFP2_NoTradePermanentCompetitorSeed.report.json",
    "PR168_GFP2_ExecutionAdjustedRankingSeed.report.json",
    "PR168_GFP2_TCADecompositionSeed.report.json",
    "PR168_GFP2_TCAComponentFormulaRegistry.report.json",
    "PR168_GFP2_OverfitFDRTrialFamilyLedger.report.json",
    "PR168_GFP2_PurgedWalkForwardCPCVSeed.report.json",
    "PR168_GFP2_CapacityCrowdingLimitSeed.report.json",
    "PR168_GFP2_ProbabilityCalibrationSeed.report.json",
    "PR168_GFP2_DataQualitySampleSizeLCBRegistry.report.json",
    "PR168_GFP2_PortfolioDiversificationMarginalUtilitySeed.report.json",
    "PR168_GFP2_ChampionChallengerNoTradeSeed.report.json",
    "PR168_GFP2_RegimeConditionedMemorySeed.report.json",
    "PR168_GFP2_MarginalUtilitySelectionSeed.report.json",
    "PR168_GFP2_OptimizerDefaultAndParameterRangeSeed.report.json",
    "PR168_GFP2_NegativeToPositiveRecoveryOpportunityLedger.report.json",
    "PR168_GFP2_NegativeCandidateRepairLadderQueue.report.json",
    "PR168_GFP2_RecoveryDimensionDiagnosis.report.json",
    "PR168_GFP2_RecoveryEligibleCandidateStackQueue.report.json",
    "PR168_GFP2_RealNegativeAfterRecoveryProofRequirements.report.json",
    "PR168_GFP2_ConditionScopedNegativeMemorySeed.report.json",
    "PR168_GFP2_RecoveryRetestToPR168_RP2Handoff.report.json",
    "PR168_GFP2_QuantumStructuralReadinessFullUniverse.report.json",
    "PR168_GFP2_QuantumObjectiveCoefficientConstraintMap.report.json",
    "PR168_GFP2_QUBO_BQM_CQM_Ising_QuadraticProgramMappingQueue.report.json",
    "PR168_GFP2_QuantumPenaltyScalingGapQueue.report.json",
    "PR168_GFP2_ClassicalFallbackComparatorMap.report.json",
    "PR168_GFP2_QuantumInterpretBackMapRepairQueue.report.json",
    "PR168_GFP2_NoQuantumBackendNoAdvantageAudit.report.json",
    "PR168_GFP2_QuantumPortfolioStackSelectionObjectiveSeed.report.json",
    "PR168_GFP2_QuantumClassicalComparatorRaceSeed.report.json",
    "PR168_GFP2_AgentRosterDiscoveryAuditConsumption.report.json",
    "PR168_GFP2_AgentDutySourceCrosswalkConsumption.report.json",
    "PR168_GFP2_AgentConsumableQKURoutingLedger.report.json",
    "PR168_GFP2_AgentConsumableFormulaRoutingLedger.report.json",
    "PR168_GFP2_AgentConsumableDataValueRoutingLedger.report.json",
    "PR168_GFP2_AgentConsumableRecoveryQueueRoutingLedger.report.json",
    "PR168_GFP2_AgentConsumableQuantumMappingRoutingLedger.report.json",
    "PR168_GFP2_AgentConsumablePriorResultCorrectionRoutingLedger.report.json",
    "PR168_GFP2_ArtifactInformationValueDAG.report.json",
    "PR168_GFP2_AgentDutyDAG.report.json",
    "PR168_GFP2_NoOrphanProof.report.json",
    "PR168_GFP2_FileValueUpstreamDownstreamOrchestrationMatrix.report.json",
    "PR168_GFP2_TerminalArtifactExceptionLedger.report.json",
    "PR168_GFP2_To_PR168_RP2_RealMarketReplayRecompute.report.json",
    "PR168_GFP2_To_PR168_RANK2_ProvenanceAwareRankingSeed.report.json",
    "PR168_GFP2_To_PR162E_PluginIntakeCandidateQueue.report.json",
    "PR168_GFP2_To_PR162D_R3_ExternalAcquisitionRepairQueue.report.json",
    "PR168_GFP2_To_PR165_B_NegativeMemorySeed.report.json",
    "PR168_GFP2_To_PR167_OpenTradeCombinationReadiness.report.json",
    "PR168_GFP2_To_RuntimeFormulaAllowlistHotPathCacheSeed.report.json",
    "PR168_GFP2_To_DashboardFormulaTradeControlSeed.report.json",
    "PR168_GFP2_FinalSummary.report.json",
)
