#!/usr/bin/env python3
"""Bounded candidate formula templates for PR168-GFP2R."""

from __future__ import annotations

from typing import Any


def formula_templates() -> list[dict[str, Any]]:
    return [
        {
            "template_id": "market_implied_probability_baseline",
            "parent_formula_id": "PR168_GFP_FORMULA_MARKET_IMPLIED_PROBABILITY",
            "formula_expression_canonical": "entry_price / payout_value",
            "required_formula_inputs": ["entry_price", "payout_value"],
            "output_unit": "probability",
            "data_families": ["current_orderbook_snapshot", "market_lifecycle"],
            "compute_kind": "market_implied_probability",
            "complexity_score": 1,
        },
        {
            "template_id": "break_even_probability_after_costs",
            "parent_formula_id": "PR168_GFP2R_FORMULA_BREAK_EVEN_PROBABILITY_AFTER_COSTS",
            "formula_expression_canonical": "(entry_price + candidate_cost_stack) / payout_value",
            "required_formula_inputs": ["entry_price", "candidate_cost_stack", "payout_value"],
            "output_unit": "probability",
            "data_families": ["current_orderbook_snapshot", "fee_tick_min_size_if_present"],
            "compute_kind": "break_even_probability",
            "complexity_score": 2,
        },
        {
            "template_id": "required_probability_edge",
            "parent_formula_id": "PR168_GFP2R_FORMULA_REQUIRED_PROBABILITY_EDGE",
            "formula_expression_canonical": "break_even_probability_after_costs - market_implied_probability",
            "required_formula_inputs": ["break_even_probability_after_costs", "market_implied_probability"],
            "output_unit": "probability_edge",
            "data_families": ["current_orderbook_snapshot", "fee_tick_min_size_if_present"],
            "compute_kind": "required_probability_edge",
            "complexity_score": 2,
        },
        {
            "template_id": "spread_depth_execution_cost",
            "parent_formula_id": "PR168_GFP_FORMULA_SPREAD_COST",
            "formula_expression_canonical": "half_spread + depth_slippage_seed",
            "required_formula_inputs": ["spread", "depth"],
            "output_unit": "dollars_per_contract",
            "data_families": ["current_orderbook_snapshot", "forward_l2_after_capture_start"],
            "compute_kind": "spread_depth_execution_cost",
            "complexity_score": 3,
        },
        {
            "template_id": "fillable_size_at_price_band",
            "parent_formula_id": "PR168_GFP2R_FORMULA_FILLABLE_SIZE_AT_PRICE_BAND",
            "formula_expression_canonical": "sum(size for level where price <= entry_price + price_band)",
            "required_formula_inputs": ["orderbook_levels", "entry_price", "price_band"],
            "output_unit": "contracts",
            "data_families": ["current_orderbook_snapshot"],
            "compute_kind": "fillable_size_at_price_band",
            "complexity_score": 3,
        },
        {
            "template_id": "fillable_size_at_edge_band",
            "parent_formula_id": "PR168_GFP2R_FORMULA_FILLABLE_SIZE_AT_EDGE_BAND",
            "formula_expression_canonical": "sum(size for level where required_edge <= edge_band)",
            "required_formula_inputs": ["orderbook_levels", "entry_price", "edge_band"],
            "output_unit": "contracts",
            "data_families": ["current_orderbook_snapshot"],
            "compute_kind": "fillable_size_at_edge_band",
            "complexity_score": 3,
        },
        {
            "template_id": "orderbook_imbalance",
            "parent_formula_id": "PR168_GFP2R_FORMULA_ORDERBOOK_IMBALANCE",
            "formula_expression_canonical": "(bid_depth - ask_depth) / (bid_depth + ask_depth)",
            "required_formula_inputs": ["bid_depth", "ask_depth"],
            "output_unit": "ratio",
            "data_families": ["current_orderbook_snapshot"],
            "compute_kind": "orderbook_imbalance",
            "complexity_score": 2,
        },
        {
            "template_id": "book_slope_proxy",
            "parent_formula_id": "PR168_GFP2R_FORMULA_BOOK_SLOPE_PROXY",
            "formula_expression_canonical": "spread / max(depth, 1)",
            "required_formula_inputs": ["spread", "depth"],
            "output_unit": "dollars_per_contract_per_contract",
            "data_families": ["current_orderbook_snapshot"],
            "compute_kind": "book_slope_proxy",
            "complexity_score": 2,
        },
        {
            "template_id": "short_horizon_price_momentum",
            "parent_formula_id": "PR168_GFP2R_FORMULA_SHORT_HORIZON_PRICE_MOMENTUM",
            "formula_expression_canonical": "last_price - first_price",
            "required_formula_inputs": ["price_history"],
            "output_unit": "dollars_per_contract",
            "data_families": ["price_history", "historical_candle"],
            "compute_kind": "short_horizon_price_momentum",
            "complexity_score": 2,
        },
        {
            "template_id": "price_history_volatility_proxy",
            "parent_formula_id": "PR168_GFP2R_FORMULA_PRICE_HISTORY_VOLATILITY_PROXY",
            "formula_expression_canonical": "standard_deviation(price_returns)",
            "required_formula_inputs": ["price_history"],
            "output_unit": "dollars_per_contract",
            "data_families": ["price_history", "historical_candle"],
            "compute_kind": "price_history_volatility_proxy",
            "complexity_score": 3,
        },
        {
            "template_id": "latency_decay_proxy",
            "parent_formula_id": "PR168_GFP_FORMULA_LATENCY_DECAY",
            "formula_expression_canonical": "staleness_seconds * volatility_proxy / 86400",
            "required_formula_inputs": ["freshness_seconds", "volatility_proxy"],
            "output_unit": "probability_edge",
            "data_families": ["data_quality_score_non_proof", "price_history"],
            "compute_kind": "latency_decay_proxy",
            "complexity_score": 3,
        },
        {
            "template_id": "capacity_depth_penalty",
            "parent_formula_id": "PR168_GFP_FORMULA_CAPACITY_CROWDING",
            "formula_expression_canonical": "order_size_bucket / max(top_level_depth, 1)",
            "required_formula_inputs": ["order_size_bucket", "top_level_depth"],
            "output_unit": "ratio",
            "data_families": ["current_orderbook_snapshot"],
            "compute_kind": "capacity_depth_penalty",
            "complexity_score": 2,
        },
        {
            "template_id": "fee_tick_min_size_threshold",
            "parent_formula_id": "PR168_GFP_FORMULA_EXPLICIT_FEE_COST",
            "formula_expression_canonical": "explicit_fee + tick_size * min_order_size",
            "required_formula_inputs": ["explicit_fee", "tick_size", "min_order_size"],
            "output_unit": "dollars_per_contract",
            "data_families": ["fee_tick_min_size_if_present"],
            "compute_kind": "fee_tick_min_size_threshold",
            "complexity_score": 2,
        },
        {
            "template_id": "time_to_resolution_lifecycle_feature",
            "parent_formula_id": "PR168_GFP2R_FORMULA_TIME_TO_RESOLUTION_LIFECYCLE_FEATURE",
            "formula_expression_canonical": "resolution_timestamp - snapshot_timestamp",
            "required_formula_inputs": ["snapshot_timestamp", "resolution_timestamp"],
            "output_unit": "seconds",
            "data_families": ["market_lifecycle", "resolution_or_settlement_if_present"],
            "compute_kind": "time_to_resolution_lifecycle_feature",
            "complexity_score": 1,
        },
        {
            "template_id": "no_trade_threshold",
            "parent_formula_id": "PR168_GFP2R_FORMULA_NO_TRADE_THRESHOLD",
            "formula_expression_canonical": "candidate_cost_stack + missing_probability_penalty",
            "required_formula_inputs": ["candidate_cost_stack", "independent_probability_state"],
            "output_unit": "probability_edge",
            "data_families": ["current_orderbook_snapshot", "data_quality_score_non_proof"],
            "compute_kind": "no_trade_threshold",
            "complexity_score": 2,
        },
        {
            "template_id": "candidate_expected_value_if_independent_probability_exists",
            "parent_formula_id": "PR168_GFP_FORMULA_BINARY_CONTRACT_EXPECTED_VALUE",
            "formula_expression_canonical": "p_resolve_yes_candidate * payout_value - entry_price - candidate_cost_stack",
            "required_formula_inputs": [
                "p_resolve_yes_candidate",
                "payout_value",
                "entry_price",
                "candidate_cost_stack",
            ],
            "output_unit": "dollars_per_contract",
            "data_families": ["current_orderbook_snapshot"],
            "compute_kind": "candidate_expected_value_if_independent_probability_exists",
            "complexity_score": 3,
        },
        {
            "template_id": "scenario_ladder_stress_candidate",
            "parent_formula_id": "PR168_GFP2R_FORMULA_SCENARIO_LADDER_STRESS_CANDIDATE",
            "formula_expression_canonical": "break_even_probability_after_costs + stress_cost_multiplier * candidate_cost_stack",
            "required_formula_inputs": ["break_even_probability_after_costs", "candidate_cost_stack"],
            "output_unit": "probability",
            "data_families": ["current_orderbook_snapshot", "price_history", "data_quality_score_non_proof"],
            "compute_kind": "scenario_ladder_stress_candidate",
            "complexity_score": 3,
        },
        {
            "template_id": "quantum_candidate_stack_variant",
            "parent_formula_id": "PR168_GFP_FORMULA_QUBO_OBJECTIVE",
            "formula_expression_canonical": "linear_quality_i * x_i - cost_penalty_i * x_i - concentration_penalty_ij * x_i * x_j",
            "required_formula_inputs": ["candidate_quality_i", "cost_penalty_i", "constraint_refs"],
            "output_unit": "objective_coefficient",
            "data_families": ["current_orderbook_snapshot", "data_quality_score_non_proof"],
            "compute_kind": "quantum_candidate_stack_variant",
            "complexity_score": 4,
        },
    ]
