from __future__ import annotations

from typing import Any

from tools.pr168_map3_report_writer import CREATED_AT_UTC, common_route


MATERIALIZED = "MATERIALIZED_FORMULA_PLUGIN_CONTRACT"
SEMANTIC_REPAIR = "SEMANTIC_FORMULA_CANDIDATE_REQUIRES_EXPRESSION_REPAIR"
SOURCE_REVIEW = "SOURCE_EVIDENCE_REVIEW_REQUIRED"
REJECTED = "REJECTED_WITH_REASON"


MANDATORY_FORMULA_FAMILIES = [
    "market_implied_probability_and_parity",
    "break_even_and_required_edge",
    "expected_value_and_payoff",
    "orderbook_microstructure",
    "trade_price_history_features",
    "tca_implementation_shortfall",
    "fill_latency_capacity",
    "calibration_and_scoring",
    "fdr_and_overfit_controls",
    "portfolio_and_marginal_utility",
    "regime_and_scenario_ladder",
    "source_evidence_and_data_quality",
    "quantum_forward_optimization",
    "venue_mechanics_constraints",
]


def _source(
    row_id: str,
    family: str,
    query: str,
    url: str,
    title: str,
    tier: str,
    formula_family: str,
    expression: str,
    inputs: list[str],
    materialization_path: str,
    data_family: str,
    units: list[str],
    route: str = "PR168_RP2_REPLAY_PAPER_RECOMPUTE",
    rejected: bool = False,
    reject_reason: str | None = None,
) -> dict[str, Any]:
    row = {
        "scout_row_id": row_id,
        "query_family": family,
        "query_text_or_source_url": query,
        "source_url": url,
        "source_title": title,
        "source_tier": tier,
        "retrieved_at_utc": CREATED_AT_UTC,
        "useful_formula_or_input_found_flag": not rejected,
        "formula_family_candidate": formula_family,
        "candidate_expression_or_semantic_definition": expression,
        "required_inputs_candidate": inputs,
        "data_family_requirements": [data_family],
        "unit_requirements": units,
        "candidate_only_flag": True,
        "accepted_truth_flag": False,
        "rejected_flag": rejected,
        "reject_reason_if_any": reject_reason,
        "source_evidence_review_route": "SOURCE_EVIDENCE_REVIEW",
        "RP2_or_RANK2_route_if_computable": route,
        "materialization_path": materialization_path,
        "formula_intake_state": materialization_path,
        "authority_class": "EXTERNAL_CANDIDATE_NON_PROOF",
        "not_profit_proof_flag": True,
        "champion_allowed_flag": False,
        "live_candidate_allowed_flag": False,
        **common_route("EXTERNAL_CANDIDATE_NON_PROOF"),
    }
    row["source_refs"] = [url]
    return row


ONLINE_SCOUT_ROWS = [
    _source(
        "SCOUT_KALSHI_ORDERBOOK_001",
        "kalshi_venue_mechanics",
        "Kalshi orderbook endpoint YES NO bids semantics",
        "https://docs.kalshi.com/api-reference/market/get-market-orderbook",
        "Kalshi Get Market Orderbook",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "market_implied_probability_and_parity",
        "yes_ask_price = payout_value - no_bid_price",
        ["payout_value", "no_bid_price"],
        MATERIALIZED,
        "kalshi_orderbook",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_KALSHI_ORDERBOOK_002",
        "kalshi_venue_mechanics",
        "Kalshi orderbook responses reciprocal YES NO bids",
        "https://docs.kalshi.com/getting_started/orderbook_responses",
        "Kalshi Orderbook Responses",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "market_implied_probability_and_parity",
        "no_ask_price = payout_value - yes_bid_price",
        ["payout_value", "yes_bid_price"],
        MATERIALIZED,
        "kalshi_orderbook",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_KALSHI_ORDERBOOK_003",
        "kalshi_venue_mechanics",
        "Kalshi orderbook spread reconstruction from YES NO bids",
        "https://docs.kalshi.com/api-reference/market/get-multiple-market-orderbooks",
        "Kalshi Get Multiple Market Orderbooks",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "orderbook_microstructure",
        "reconstructed_yes_spread = (payout_value - no_bid_price) - yes_bid_price",
        ["payout_value", "no_bid_price", "yes_bid_price"],
        MATERIALIZED,
        "kalshi_orderbook",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_KALSHI_TRADES_001",
        "kalshi_venue_mechanics",
        "Kalshi trades API",
        "https://docs.kalshi.com/api-reference/market/get-trades",
        "Kalshi Get Trades",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "trade_price_history_features",
        "trade_rate = trade_count / lookback_seconds",
        ["trade_count", "lookback_seconds"],
        MATERIALIZED,
        "kalshi_trades",
        ["count", "seconds"],
    ),
    _source(
        "SCOUT_KALSHI_CANDLES_001",
        "kalshi_venue_mechanics",
        "Kalshi candlesticks historical prices",
        "https://docs.kalshi.com/api-reference/historical/get-historical-market-candlesticks",
        "Kalshi Historical Market Candlesticks",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "trade_price_history_features",
        "candlestick_return = close_price - open_price",
        ["close_price", "open_price"],
        MATERIALIZED,
        "kalshi_candlesticks",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_KALSHI_CANDLES_002",
        "kalshi_venue_mechanics",
        "Kalshi market candlesticks live and historical cutoff",
        "https://docs.kalshi.com/api-reference/market/get-market-candlesticks",
        "Kalshi Get Market Candlesticks",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "regime_and_scenario_ladder",
        "candlestick_freshness_gap_seconds = current_timestamp - candle_end_timestamp",
        ["current_timestamp", "candle_end_timestamp"],
        MATERIALIZED,
        "kalshi_candlesticks",
        ["seconds"],
    ),
    _source(
        "SCOUT_KALSHI_WS_001",
        "kalshi_venue_mechanics",
        "Kalshi WebSocket orderbook updates",
        "https://docs.kalshi.com/websockets/orderbook-updates",
        "Kalshi Orderbook Updates WebSocket",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "fill_latency_capacity",
        "staleness_penalty = edge_value * min(latency_seconds * decay_rate, 1)",
        ["edge_value", "latency_seconds", "decay_rate"],
        MATERIALIZED,
        "kalshi_websocket",
        ["edge", "seconds", "rate"],
    ),
    _source(
        "SCOUT_KALSHI_WS_002",
        "kalshi_venue_mechanics",
        "Kalshi WebSocket market data quick start",
        "https://docs.kalshi.com/getting_started/quick_start_websockets",
        "Kalshi Quick Start WebSockets",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "regime_and_scenario_ladder",
        "market_update_rate = websocket_update_count / lookback_seconds",
        ["websocket_update_count", "lookback_seconds"],
        MATERIALIZED,
        "kalshi_websocket",
        ["count", "seconds"],
    ),
    _source(
        "SCOUT_KALSHI_FEE_001",
        "kalshi_venue_mechanics",
        "Kalshi fees API fee schedule",
        "https://kalshi.com/docs/kalshi-fee-schedule.pdf",
        "Kalshi Fee Schedule",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "break_even_and_required_edge",
        "kalshi_fee_candidate = ceil_cent(0.035 * contract_count * price * (1 - price))",
        ["contract_count", "price"],
        SEMANTIC_REPAIR,
        "kalshi_fee_schedule",
        ["contracts", "probability_price_0_to_1", "cents"],
    ),
    _source(
        "SCOUT_KALSHI_TICK_001",
        "kalshi_venue_mechanics",
        "Kalshi tick size min order size public docs",
        "https://docs.kalshi.com/getting_started/fixed_point_migration",
        "Kalshi Fixed-Point Migration",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "venue_mechanics_constraints",
        "tick_size_gap_route = price_level_structure requires venue source evidence before replay use",
        ["price_level_structure", "order_price"],
        SOURCE_REVIEW,
        "kalshi_market_constraints",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_POLY_BOOK_001",
        "polymarket_venue_mechanics",
        "Polymarket CLOB book API",
        "https://docs.polymarket.com/api-reference/market-data/get-order-book",
        "Polymarket Get Order Book",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "orderbook_microstructure",
        "book_spread = best_ask - best_bid",
        ["best_ask", "best_bid"],
        MATERIALIZED,
        "polymarket_clob_book",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_POLY_BOOK_002",
        "polymarket_venue_mechanics",
        "Polymarket orderbook public endpoint",
        "https://docs.polymarket.com/trading/orderbook",
        "Polymarket Orderbook",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "fill_latency_capacity",
        "fillable_quantity = min(order_size, depth_at_limit)",
        ["order_size", "depth_at_limit"],
        MATERIALIZED,
        "polymarket_clob_book",
        ["contracts"],
    ),
    _source(
        "SCOUT_POLY_HISTORY_001",
        "polymarket_venue_mechanics",
        "Polymarket prices-history API",
        "https://docs.polymarket.com/api-reference/markets/get-prices-history",
        "Polymarket Get Prices History",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "trade_price_history_features",
        "price_history_return = current_price - prior_price",
        ["current_price", "prior_price"],
        MATERIALIZED,
        "polymarket_prices_history",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_POLY_MID_001",
        "polymarket_venue_mechanics",
        "Polymarket midpoint API",
        "https://docs.polymarket.com/api-reference/data/get-midpoint-price",
        "Polymarket Get Midpoint Price",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "market_implied_probability_and_parity",
        "midpoint_probability = (best_bid + best_ask) / 2",
        ["best_bid", "best_ask"],
        MATERIALIZED,
        "polymarket_clob_midpoint",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_POLY_SPREAD_001",
        "polymarket_venue_mechanics",
        "Polymarket spread API",
        "https://docs.polymarket.com/api-reference/market-data/get-spreads",
        "Polymarket Get Spreads",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "orderbook_microstructure",
        "spread_cost = spread * contract_count",
        ["spread", "contract_count"],
        MATERIALIZED,
        "polymarket_clob_spread",
        ["probability_price_0_to_1", "contracts"],
    ),
    _source(
        "SCOUT_POLY_LAST_001",
        "polymarket_venue_mechanics",
        "Polymarket last trade price API",
        "https://docs.polymarket.com/api-reference/market-data/get-last-trade-price",
        "Polymarket Get Last Trade Price",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "trade_price_history_features",
        "last_trade_momentum = last_trade_price - prior_trade_price",
        ["last_trade_price", "prior_trade_price"],
        MATERIALIZED,
        "polymarket_clob_trades",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_POLY_TICK_001",
        "polymarket_venue_mechanics",
        "Polymarket fee rate tick size",
        "https://docs.polymarket.com/trading/clients/public",
        "Polymarket Public Methods",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "venue_mechanics_constraints",
        "fee_rate_cost = notional * fee_rate_bps / 10000",
        ["notional", "fee_rate_bps"],
        MATERIALIZED,
        "polymarket_clob_market_info",
        ["currency", "basis_points"],
    ),
    _source(
        "SCOUT_POLY_WS_001",
        "polymarket_venue_mechanics",
        "Polymarket market WebSocket",
        "https://docs.polymarket.com/market-data/websocket/market-channel",
        "Polymarket Market Channel",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "fill_latency_capacity",
        "websocket_staleness_seconds = current_timestamp - message_timestamp",
        ["current_timestamp", "message_timestamp"],
        MATERIALIZED,
        "polymarket_websocket",
        ["seconds"],
    ),
    _source(
        "SCOUT_PM_EV_001",
        "prediction_market_formulas",
        "binary prediction-market expected value formula",
        "https://rodneywhitecenter.wharton.upenn.edu/wp-content/uploads/2014/04/0611.pdf",
        "Interpreting Prediction Market Prices as Probabilities",
        "RESEARCH_PAPER_CANDIDATE",
        "expected_value_and_payoff",
        "expected_gross_pnl = independent_probability * payout_value - entry_price",
        ["independent_probability", "payout_value", "entry_price"],
        MATERIALIZED,
        "prediction_market_probability",
        ["probability", "currency"],
    ),
    _source(
        "SCOUT_PM_BREAKEVEN_001",
        "prediction_market_formulas",
        "break-even probability after fees",
        "https://www.tradealgo.com/trading-guides/prediction-markets/prediction-market-pricing",
        "Prediction Market Pricing",
        "NON_OFFICIAL_CANDIDATE",
        "break_even_and_required_edge",
        "break_even_probability_after_costs = (entry_price + total_fee_per_contract) / payout_value",
        ["entry_price", "total_fee_per_contract", "payout_value"],
        MATERIALIZED,
        "prediction_market_costs",
        ["currency", "probability"],
    ),
    _source(
        "SCOUT_PM_PARITY_001",
        "prediction_market_formulas",
        "YES NO parity and arbitrage",
        "https://www.tradealgo.com/trading-guides/prediction-markets/prediction-market-arbitrage-guide",
        "Prediction Market Arbitrage",
        "NON_OFFICIAL_CANDIDATE",
        "market_implied_probability_and_parity",
        "yes_no_parity_gap = abs(yes_price + no_price - payout_value)",
        ["yes_price", "no_price", "payout_value"],
        MATERIALIZED,
        "prediction_market_parity",
        ["probability_price_0_to_1"],
    ),
    _source(
        "SCOUT_PM_ARBITRAGE_001",
        "prediction_market_formulas",
        "prediction market arbitrage formulas",
        "https://quantpedia.com/systematic-edges-in-prediction-markets/",
        "Systematic Edges in Prediction Markets",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "market_implied_probability_and_parity",
        "buy_all_margin = payout_value - sum_outcome_prices",
        ["payout_value", "sum_outcome_prices"],
        MATERIALIZED,
        "prediction_market_parity",
        ["currency"],
    ),
    _source(
        "SCOUT_FILL_001",
        "execution_tca_fill_latency_capacity",
        "limit-order fill probability depth fillability",
        "https://questdb.com/glossary/fill-probability/",
        "Fill Probability",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "fill_latency_capacity",
        "depth_fill_probability_proxy = min(depth_at_limit / order_size, 1)",
        ["depth_at_limit", "order_size"],
        MATERIALIZED,
        "orderbook_depth",
        ["contracts"],
    ),
    _source(
        "SCOUT_FILL_002",
        "execution_tca_fill_latency_capacity",
        "limit order fill probability order book depth",
        "https://arxiv.org/pdf/2403.02572",
        "Fill Probabilities in a Limit Order Book with State-Dependent Stochastic Order Flows",
        "RESEARCH_PAPER_CANDIDATE",
        "fill_latency_capacity",
        "state_dependent_fill_model requires queue and stochastic flow inputs before expression materialization",
        ["queue_position", "arrival_rate", "cancel_rate", "market_order_rate"],
        SEMANTIC_REPAIR,
        "orderbook_depth",
        ["contracts", "rate"],
    ),
    _source(
        "SCOUT_MICRO_001",
        "execution_tca_fill_latency_capacity",
        "orderbook imbalance microprice",
        "https://hftbacktest.readthedocs.io/en/latest/tutorials/Market%20Making%20with%20Alpha%20-%20Order%20Book%20Imbalance.html",
        "Order Book Imbalance",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "orderbook_microstructure",
        "orderbook_imbalance = (bid_depth - ask_depth) / (bid_depth + ask_depth)",
        ["bid_depth", "ask_depth"],
        MATERIALIZED,
        "orderbook_depth",
        ["contracts"],
    ),
    _source(
        "SCOUT_MICRO_002",
        "execution_tca_fill_latency_capacity",
        "microprice formula orderbook imbalance",
        "https://databento.com/docs/examples/order-book/microprice",
        "Microprice and Book Imbalance",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "orderbook_microstructure",
        "microprice_proxy = (best_ask * bid_depth + best_bid * ask_depth) / (bid_depth + ask_depth)",
        ["best_ask", "bid_depth", "best_bid", "ask_depth"],
        MATERIALIZED,
        "orderbook_depth",
        ["probability_price_0_to_1", "contracts"],
    ),
    _source(
        "SCOUT_TCA_001",
        "execution_tca_fill_latency_capacity",
        "implementation shortfall formula",
        "https://www.investopedia.com/terms/i/implementationshortfall.asp",
        "Implementation Shortfall",
        "INSTITUTIONAL_METHOD_CANDIDATE",
        "tca_implementation_shortfall",
        "implementation_shortfall = average_execution_price - decision_price + explicit_fee + opportunity_cost",
        ["average_execution_price", "decision_price", "explicit_fee", "opportunity_cost"],
        SEMANTIC_REPAIR,
        "execution_tca",
        ["currency"],
    ),
    _source(
        "SCOUT_TCA_002",
        "execution_tca_fill_latency_capacity",
        "transaction cost analysis spread slippage adverse selection",
        "https://www.talos.com/insights/understanding-crypto-transaction-cost-analysis",
        "Understanding Transaction Cost Analysis",
        "INSTITUTIONAL_METHOD_CANDIDATE",
        "tca_implementation_shortfall",
        "tca_total_candidate = spread_cost + slippage_cost + explicit_fee + adverse_selection_cost",
        ["spread_cost", "slippage_cost", "explicit_fee", "adverse_selection_cost"],
        MATERIALIZED,
        "execution_tca",
        ["currency"],
    ),
    _source(
        "SCOUT_LATENCY_001",
        "execution_tca_fill_latency_capacity",
        "latency decay trading signal formula staleness penalty",
        "https://a-teaminsight.com/blog/latency-in-electronic-trading/",
        "Latency in Electronic Trading",
        "INSTITUTIONAL_METHOD_CANDIDATE",
        "fill_latency_capacity",
        "latency_decay_edge = edge_value * (1 - min(latency_seconds * decay_rate, 1))",
        ["edge_value", "latency_seconds", "decay_rate"],
        MATERIALIZED,
        "latency",
        ["edge", "seconds", "rate"],
    ),
    _source(
        "SCOUT_CALIB_BRIER_001",
        "calibration_fdr_overfit",
        "Brier score formula",
        "https://scikit-learn.org/stable/modules/generated/sklearn.metrics.brier_score_loss.html",
        "scikit-learn brier_score_loss",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "calibration_and_scoring",
        "brier_score = (predicted_probability - outcome) ** 2",
        ["predicted_probability", "outcome"],
        MATERIALIZED,
        "calibration",
        ["probability", "binary_outcome"],
    ),
    _source(
        "SCOUT_CALIB_ECE_001",
        "calibration_fdr_overfit",
        "expected calibration error formula",
        "https://lightning.ai/docs/torchmetrics/stable/classification/calibration_error.html",
        "TorchMetrics Calibration Error",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "calibration_and_scoring",
        "expected_calibration_error = bucket_weight * abs(bucket_accuracy - bucket_confidence)",
        ["bucket_weight", "bucket_accuracy", "bucket_confidence"],
        MATERIALIZED,
        "calibration",
        ["probability"],
    ),
    _source(
        "SCOUT_CALIB_LOGLOSS_001",
        "calibration_fdr_overfit",
        "log loss formula probability forecast",
        "https://scikit-learn.org/stable/modules/calibration.html",
        "scikit-learn Probability Calibration",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "calibration_and_scoring",
        "log_loss requires clipped probability and log transform before safe expression materialization",
        ["predicted_probability_clipped", "outcome"],
        SEMANTIC_REPAIR,
        "calibration",
        ["probability", "binary_outcome"],
    ),
    _source(
        "SCOUT_FDR_BH_001",
        "calibration_fdr_overfit",
        "Benjamini-Hochberg FDR formula",
        "https://en.wikipedia.org/wiki/False_discovery_rate",
        "False Discovery Rate",
        "RESEARCH_PAPER_CANDIDATE",
        "fdr_and_overfit_controls",
        "benjamini_hochberg_threshold = alpha * rank_index / trial_count",
        ["alpha", "rank_index", "trial_count"],
        MATERIALIZED,
        "overfit_fdr",
        ["probability", "rank", "count"],
    ),
    _source(
        "SCOUT_FDR_DSR_001",
        "calibration_fdr_overfit",
        "Deflated Sharpe Ratio formula",
        "https://www.davidhbailey.com/dhbpapers/deflated-sharpe.pdf",
        "The Deflated Sharpe Ratio",
        "RESEARCH_PAPER_CANDIDATE",
        "fdr_and_overfit_controls",
        "deflated_sharpe_ratio requires return skew, kurtosis, trial count, and benchmark SR inputs before expression repair",
        ["observed_sharpe", "return_skew", "return_kurtosis", "trial_count"],
        SEMANTIC_REPAIR,
        "overfit_fdr",
        ["ratio"],
    ),
    _source(
        "SCOUT_FDR_CPCV_001",
        "calibration_fdr_overfit",
        "purged cross validation CPCV financial machine learning",
        "https://www.quantbeckman.com/p/with-code-combinatorial-purged-cross",
        "Combinatorial Purged Cross Validation",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "fdr_and_overfit_controls",
        "cpcv_gap_route requires split, purge, embargo, and label-overlap contracts",
        ["split_id", "purge_window", "embargo_window", "label_interval"],
        SOURCE_REVIEW,
        "overfit_fdr",
        ["time_window"],
    ),
    _source(
        "SCOUT_PORT_KELLY_001",
        "portfolio_marginal_regime",
        "Kelly criterion fractional Kelly prediction market",
        "https://en.wikipedia.org/wiki/Kelly_criterion",
        "Kelly Criterion",
        "RESEARCH_PAPER_CANDIDATE",
        "portfolio_and_marginal_utility",
        "fractional_kelly = kelly_scale * ((independent_probability * net_odds - (1 - independent_probability)) / net_odds)",
        ["kelly_scale", "independent_probability", "net_odds"],
        MATERIALIZED,
        "portfolio_sizing",
        ["probability", "odds"],
    ),
    _source(
        "SCOUT_PORT_KELLY_002",
        "portfolio_marginal_regime",
        "Kelly criterion prediction markets candidate lead",
        "https://www.bettoredge.com/post/kelly-criterion-prediction-markets",
        "Using Kelly Criterion with Prediction Markets",
        "NON_OFFICIAL_CANDIDATE",
        "portfolio_and_marginal_utility",
        "fractional Kelly candidate requires source evidence and independent probability calibration before sizing use",
        ["kelly_scale", "independent_probability", "net_odds"],
        SOURCE_REVIEW,
        "portfolio_sizing",
        ["probability", "odds"],
    ),
    _source(
        "SCOUT_PORT_CONC_001",
        "portfolio_marginal_regime",
        "portfolio concentration penalty formula",
        "https://www.wallstreetmojo.com/portfolio-concentration/",
        "Portfolio Concentration",
        "NON_OFFICIAL_CANDIDATE",
        "portfolio_and_marginal_utility",
        "concentration_penalty = concentration_lambda * venue_exposure_share ** 2",
        ["concentration_lambda", "venue_exposure_share"],
        MATERIALIZED,
        "portfolio_exposure",
        ["weight"],
    ),
    _source(
        "SCOUT_PORT_CORR_001",
        "portfolio_marginal_regime",
        "correlation clustering portfolio risk",
        "https://fsc.stevens.edu/network-and-clustering-based-portfolio-optimization-enhancing-risk-adjusted-performance-through-diversification/",
        "Network and Clustering Based Portfolio Optimization",
        "RESEARCH_PAPER_CANDIDATE",
        "portfolio_and_marginal_utility",
        "correlation_penalty = correlation_lambda * exposure_i * exposure_j * correlation_ij",
        ["correlation_lambda", "exposure_i", "exposure_j", "correlation_ij"],
        MATERIALIZED,
        "portfolio_correlation",
        ["weight", "correlation"],
    ),
    _source(
        "SCOUT_REGIME_001",
        "portfolio_marginal_regime",
        "liquidity spread volatility regime trading",
        "https://questdb.com/glossary/order-book-imbalance/",
        "Order Book Imbalance",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "regime_and_scenario_ladder",
        "liquidity_regime_score = 0.5 * depth_score + 0.3 * spread_score + 0.2 * freshness_score",
        ["depth_score", "spread_score", "freshness_score"],
        MATERIALIZED,
        "regime_features",
        ["score_0_to_1"],
    ),
    _source(
        "SCOUT_QISKIT_001",
        "quantum_hybrid_optimization",
        "Qiskit QuadraticProgram QUBO conversion",
        "https://qiskit-community.github.io/qiskit-optimization/tutorials/02_converters_for_quadratic_programs.html",
        "Qiskit Converters for Quadratic Programs",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "quantum_forward_optimization",
        "qiskit_qubo_conversion_route requires objective, variables, constraints, penalty source, and interpret-back map",
        ["binary_variables", "linear_coefficients", "quadratic_coefficients", "constraints", "penalty"],
        SOURCE_REVIEW,
        "quantum_optimization",
        ["coefficient", "constraint"],
        route="PR162E_Q_QUANTUM_MAPPING",
    ),
    _source(
        "SCOUT_QISKIT_002",
        "quantum_hybrid_optimization",
        "Qiskit QuadraticProgram to QUBO converter docs",
        "https://qiskit-community.github.io/qiskit-optimization/_modules/qiskit_optimization/converters/quadratic_program_to_qubo.html",
        "Qiskit QuadraticProgramToQubo",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "quantum_forward_optimization",
        "qubo_linear_coefficient = -1 * candidate_utility",
        ["candidate_utility"],
        MATERIALIZED,
        "quantum_optimization",
        ["coefficient"],
        route="PR162E_Q_QUANTUM_MAPPING",
    ),
    _source(
        "SCOUT_DWAVE_001",
        "quantum_hybrid_optimization",
        "D-Wave BQM CQM Ising QUBO model",
        "https://docs.dwavequantum.com/en/latest/concepts/models.html",
        "D-Wave Models",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "quantum_forward_optimization",
        "bqm_quadratic_penalty = penalty_lambda * selection_i * selection_j * correlation_ij",
        ["penalty_lambda", "selection_i", "selection_j", "correlation_ij"],
        MATERIALIZED,
        "quantum_optimization",
        ["coefficient", "binary"],
        route="PR162E_Q_QUANTUM_MAPPING",
    ),
    _source(
        "SCOUT_DWAVE_002",
        "quantum_hybrid_optimization",
        "QUBO penalty scaling constraints",
        "https://docs.dwavequantum.com/en/latest/quantum_research/reformulating.html",
        "D-Wave Reformulating a Problem",
        "OPEN_SOURCE_DOC_CANDIDATE",
        "quantum_forward_optimization",
        "penalty_scaling_gap_route requires documented feasible-state penalty greater than objective range",
        ["objective_range", "constraint_violation_penalty"],
        SEMANTIC_REPAIR,
        "quantum_optimization",
        ["coefficient"],
        route="PR162E_Q_QUANTUM_MAPPING",
    ),
    _source(
        "SCOUT_FORECASTEX_001",
        "forecast_event_contracts",
        "ForecastEx event contracts market data docs",
        "https://forecastex.com/data",
        "ForecastEx Data",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "source_evidence_and_data_quality",
        "forecastex_public_data_freshness = current_timestamp - csv_published_timestamp",
        ["current_timestamp", "csv_published_timestamp"],
        MATERIALIZED,
        "forecastex_public_csv",
        ["seconds"],
        route="DATA1B_MARKET_DATA_ACQUISITION_REPAIR",
    ),
    _source(
        "SCOUT_IBKR_001",
        "forecast_event_contracts",
        "IBKR ForecastEx event contracts API market data subscription docs",
        "https://www.interactivebrokers.com/campus/ibkr-api-page/event-contracts/",
        "Event Contracts in the Web API",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "source_evidence_and_data_quality",
        "ibkr_forecastex_subscription_gap_route requires eligibility and market data subscription before replay use",
        ["contract_details_available_flag", "market_data_subscription_state"],
        SOURCE_REVIEW,
        "ibkr_forecastex_event_contracts",
        ["boolean"],
        route="DATA1B_MARKET_DATA_ACQUISITION_REPAIR",
    ),
    _source(
        "SCOUT_IBKR_002",
        "forecast_event_contracts",
        "Interactive Brokers ForecastEx event contracts market data",
        "https://www.interactivebrokers.com/campus/ibkr-api-page/trader-workstation-api/",
        "TWS API Documentation",
        "OFFICIAL_PUBLIC_DOC_CANDIDATE",
        "source_evidence_and_data_quality",
        "delayed_data_candidate_flag = 1 if delayed_market_data_available else 0",
        ["delayed_market_data_available"],
        SEMANTIC_REPAIR,
        "ibkr_forecastex_event_contracts",
        ["boolean"],
        route="DATA1B_MARKET_DATA_ACQUISITION_REPAIR",
    ),
]


def materialized_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for source in ONLINE_SCOUT_ROWS:
        if source["rejected_flag"]:
            continue
        formula_id = f"FORM_MAP3_{source['scout_row_id'].replace('SCOUT_', '')}"
        row = {
            "formula_materialization_row_id": f"MAT_{source['scout_row_id']}",
            "formula_id": formula_id,
            "formula_variant_id": f"FVAR_{formula_id}_BASE",
            "external_candidate_id": f"EXT_{source['scout_row_id']}",
            "source_url": source["source_url"],
            "formula_family": source["formula_family_candidate"],
            "safe_formula_expression_or_semantic_definition": source[
                "candidate_expression_or_semantic_definition"
            ],
            "required_inputs_with_units": [
                {"input_id": item, "unit": source["unit_requirements"][0] if source["unit_requirements"] else "unspecified"}
                for item in source["required_inputs_candidate"]
            ],
            "materialization_path": source["materialization_path"],
            "computability_route": (
                "COMPUTABLE_NOW_REPLAY_PAPER_CANDIDATE"
                if source["materialization_path"] == MATERIALIZED
                else "COMPUTABLE_AFTER_FORMULA_INPUT_REPAIR"
                if source["materialization_path"] == SEMANTIC_REPAIR
                else "COMPUTABLE_AFTER_SOURCE_EVIDENCE_REVIEW"
            ),
            "formula_output_type": "candidate_numeric_or_semantic_contract",
            "candidate_only_flag": True,
            "accepted_truth_flag": False,
            "not_profit_proof_flag": True,
            "champion_allowed_flag": False,
            "live_candidate_allowed_flag": False,
            **common_route("FORMULA_MATERIALIZATION_CANDIDATE_NON_PROOF"),
        }
        row["source_refs"] = [source["source_url"]]
        row["data_requirement_refs"] = [f"DATAREQ_{formula_id}"]
        row["unit_normalization_refs"] = [f"UNIT_{formula_id}"]
        row["formula_contract_refs"] = (
            [f"FormulaPluginContractV1:{formula_id}"]
            if source["materialization_path"] == MATERIALIZED
            else []
        )
        rows.append(row)
    return rows
