#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import subprocess
import sys
import tempfile
from typing import Sequence

SUCCESS_MARKER = "QTT_VALIDATION_GATES_OK"


def _path(*parts: str) -> str:
    return str(pathlib.Path(*parts))


def _default_validation_dir() -> pathlib.Path:
    return pathlib.Path(tempfile.gettempdir()) / "qtt_validation_gates"


def build_validation_commands(
    validation_dir: pathlib.Path | str | None = None,
) -> list[list[str]]:
    validation_dir = (
        _default_validation_dir()
        if validation_dir is None
        else pathlib.Path(validation_dir)
    )
    section_manifest = validation_dir / "SectionManifest.json"
    traceability_report = validation_dir / "TraceabilityReport.json"
    first_pr_scope_report = validation_dir / "FirstPrScopeReport.json"
    master_plan = pathlib.Path("docs") / "master_plan" / "QTT_MasterPlan_Current.md"

    return [
        [
            sys.executable,
            _path("tools", "master_plan_ingest.py"),
            "--input",
            str(master_plan),
            "--section-manifest-out",
            str(section_manifest),
            "--traceability-out",
            str(traceability_report),
            "--scope-report-out",
            str(first_pr_scope_report),
        ],
        [
            sys.executable,
            _path("tools", "master_plan_traceability_check.py"),
            "--master-plan",
            str(master_plan),
            "--section-manifest",
            str(section_manifest),
            "--traceability-report",
            str(traceability_report),
        ],
        [
            sys.executable,
            _path("tools", "validate_first_pr_scope.py"),
            "--repo-root",
            ".",
            "--scope-report",
            str(first_pr_scope_report),
            "--block-runtime",
            "--block-live",
            "--block-sha",
            "--block-companion-package",
            "--block-profit-claims",
            "--block-source-retrieval",
            "--block-source-acceptance",
            "--block-connector-binding",
            "--block-private-state-fetch",
            "--block-order-execution",
            "--block-neural-training",
            "--block-neural-inference",
            "--block-external-repo-clone",
            "--block-package-install-scripts",
        ],
        [
            sys.executable,
            _path("tools", "validate_qtt_owner_global_override_authority.py"),
            "--mode",
            "dev",
            "--repo-root",
            ".",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "QTTOwnerGlobalOverrideAuthority.report.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_qtt_agent_role_operating_charter_registry.py",
            ),
            "--mode",
            "dev",
            "--repo-root",
            ".",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "QTTAgentRoleOperatingCharterReport.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_qtt_algorithm_formula_family_registry.py",
            ),
            "--mode",
            "dev",
            "--repo-root",
            ".",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "QTTAlgorithmFormulaFamilyReport.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_qtt_agent_algorithm_binding_registry.py",
            ),
            "--mode",
            "dev",
            "--repo-root",
            ".",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "QTTAgentAlgorithmBindingReport.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_qtt_agent_algorithm_consumer_gate.py",
            ),
            "--mode",
            "dev",
            "--repo-root",
            ".",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "QTTAgentAlgorithmConsumerGate.report.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_qtt_agent_algorithm_cumulative_readiness_gate.py",
            ),
            "--mode",
            "dev",
            "--repo-root",
            ".",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "QTTAgentAlgorithmCumulativeReadinessGate.report.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_qtt_agent_algorithm_command_matrix.py"),
        ],
        [
            sys.executable,
            _path("tools", "validate_source_evidence_static.py"),
            "--schema",
            _path("schemas", "source_evidence", "source_evidence.schema.json"),
            "--owner-packet",
            _path(
                "docs",
                "master_plan",
                "source_evidence",
                "QTT_OWNER_SOURCE_EVIDENCE_DEFINITIONS_PACKET.md",
            ),
            "--registry-fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "synthetic_acceptance_registry.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_source_evidence_gate_confirmation_static.py"),
            "--repo-root",
            ".",
            "--schema",
            _path(
                "schemas",
                "source_evidence",
                "source_evidence_gate_confirmation.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "synthetic_source_evidence_gate_confirmation_blocked.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_connector_capability_static.py"),
            "--schema",
            _path("schemas", "connectors", "connector_capability_registry.schema.json"),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "connectors",
                "synthetic_connector_capability_registry.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_runtime_orchestration_static.py"),
            "--schema",
            _path(
                "schemas",
                "runtime_orchestration",
                "runtime_orchestration_skeleton.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "runtime_orchestration",
                "synthetic_runtime_orchestration_skeleton.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_replay_paper_execution_graph_static.py"),
            "--schema",
            _path(
                "schemas",
                "replay_paper_review",
                "replay_paper_execution_graph.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "replay_paper_review",
                "synthetic_replay_paper_execution_graph.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_venue_abstraction_layer_static.py"),
            "--schema",
            _path("schemas", "connectors", "venue_abstraction_layer.schema.json"),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "connectors",
                "synthetic_venue_abstraction_layer.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_order_intent_execution_router_static.py"),
            "--schema",
            _path(
                "schemas",
                "connectors",
                "order_intent_execution_router_scaffolding.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "connectors",
                "synthetic_order_intent_execution_router_scaffolding.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_atomicrows_readiness_static.py"),
            "--repo-root",
            ".",
            "--schema",
            _path("schemas", "atomicrows", "atomicrows_readiness_audit.schema.json"),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "atomicrows",
                "synthetic_atomicrows_readiness_blocked.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_atomicrows_unblocking_requirements_static.py"),
            "--repo-root",
            ".",
            "--schema",
            _path(
                "schemas",
                "atomicrows",
                "atomicrows_unblocking_requirements_audit.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "atomicrows",
                "synthetic_atomicrows_unblocking_requirements_required.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_atomicrows_canonical_row_specification_static.py"),
            "--repo-root",
            ".",
            "--schema",
            _path(
                "schemas",
                "atomicrows",
                "atomicrows_canonical_row_specification_audit.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "atomicrows",
                "synthetic_atomicrows_canonical_row_specification_required.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_atomicrows_bundle_schema_checker_static.py"),
            "--repo-root",
            ".",
            "--row-schema",
            _path("schemas", "atomicrows", "atomic_parameter_row.schema.json"),
            "--bundle-schema",
            _path("schemas", "atomicrows", "atomic_row_bundle.schema.json"),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "atomicrows",
                "synthetic_atomicrows_bundle_bootstrap_absent.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "build_atomicrows_parameter_lifecycle_report.py"),
        ],
        [
            sys.executable,
            _path("tools", "validate_atomicrows_parameter_lifecycle.py"),
            "--mode",
            "dev",
        ],
        [
            sys.executable,
            _path("tools", "validate_atomicrows_lifecycle_consumer_gate.py"),
            "--mode",
            "dev",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "AtomicRowsLifecycleConsumerGate.report.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_atomicrows_lifecycle_promotion_receipt_gate.py"),
            "--mode",
            "dev",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "AtomicRowsLifecyclePromotionReceiptGate.report.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_lifecycle_registry_mutation_guard.py",
            ),
            "--mode",
            "dev",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "AtomicRowsLifecycleRegistryMutationGuard.report.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_lifecycle_cumulative_readiness_gate.py",
            ),
            "--mode",
            "dev",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "AtomicRowsLifecycleCumulativeReadinessGate.report.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_lifecycle_gate_command_matrix.py",
            ),
            "--mode",
            "dev",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "AtomicRowsLifecycleGateCommandMatrix.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_parameter_agent_binding_registry.py",
            ),
            "--mode",
            "dev",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "AtomicRowsParameterAgentBindingReport.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_parameter_agent_binding_consumer_gate.py",
            ),
            "--mode",
            "dev",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "AtomicRowsParameterAgentBindingConsumerGate.report.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_parameter_agent_binding_cumulative_readiness_gate.py",
            ),
            "--mode",
            "dev",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "AtomicRowsParameterAgentBindingCumulativeReadinessGate.report.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_parameter_agent_binding_command_matrix.py",
            ),
            "--mode",
            "dev",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "AtomicRowsParameterAgentBindingCommandMatrix.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_research_provenance_evidence_tier_classification.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_owner_submitted_research_source_intake_registry.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_research_source_to_candidate_family_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_parameter_stack_role_taxonomy.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_parameter_stack_completeness_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_parameter_stack_compatibility_gate.py",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_edge_parameter_stack_selection_packet.py"),
        ],
        [
            sys.executable,
            _path("tools", "validate_qtt_trade_context_packet.py"),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_parameter_selection_universe_registry.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_atomicrows_parameter_selection_universe_consumer_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_trade_context_selection_universe_routing_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_quantum_applicability_classification_registry.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_owner_quantum_priority_policy_registry.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_parameter_algorithm_scoring_policy_registry.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_parameter_stack_scoring_and_ranking_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_quantum_classical_optimizer_arbitration_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_candidate_parameter_stack_generation_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_trade_context_parameter_stack_selection_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_selected_parameter_stack_handoff_packet.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_replay_paper_candidate_stack_competition_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_dual_result_review_for_parameter_stacks.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_owner_live_promotion_review_for_parameter_stacks.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_owner_approval_request_queue_registry.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_owner_override_receipt_authoring_gate.py",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_owner_dashboard_approval_menu_schema.py",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_generated_derivative_bootstrap_gate_static.py"),
            "--repo-root",
            ".",
            "--schema",
            _path(
                "schemas",
                "master_plan",
                "generated_derivative_bootstrap_gate.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "master_plan",
                "synthetic_generated_derivative_bootstrap_gate.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_stage1_packet_schema_gate_static.py"),
            "--repo-root",
            ".",
            "--schema-dir",
            _path("schemas", "stage1_prediction_markets"),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "stage1_prediction_markets",
                "synthetic_stage1_packet_schema_gate_blocked.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_venue_neutral_prediction_adapter_gate_static.py"),
            "--repo-root",
            ".",
            "--schema-dir",
            _path("schemas", "venue_neutral_prediction_adapter"),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "venue_neutral_prediction_adapter",
                "synthetic_venue_neutral_prediction_adapter_gate_blocked.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_connector_scaffold_source_required_gate_static.py",
            ),
            "--repo-root",
            ".",
            "--schema",
            _path(
                "schemas",
                "connectors",
                "connector_scaffold_source_required_gate.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "connectors",
                "synthetic_connector_scaffold_source_required_blocked.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_stage1_runtime_scaffold_gate_static.py"),
            "--repo-root",
            ".",
            "--schema",
            _path(
                "schemas",
                "runtime_orchestration",
                "stage1_runtime_scaffold_gate.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "runtime_orchestration",
                "synthetic_stage1_runtime_scaffold_gate_blocked.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "validate_source_fact_binding_connector_semantic_readiness_static.py",
            ),
            "--repo-root",
            ".",
            "--source-to-connector-schema",
            _path(
                "schemas",
                "source_fact_binding_readiness",
                "stage1_source_to_connector_field_binding_matrix.schema.json",
            ),
            "--source-to-connector-fixture",
            _path(
                "tests",
                "fixtures",
                "source_fact_binding_readiness",
                "synthetic_stage1_source_to_connector_field_binding_matrix.v1.fixture.json",
            ),
            "--connector-target-schema",
            _path(
                "schemas",
                "source_fact_binding_readiness",
                "stage1_connector_semantic_target_field_matrix.schema.json",
            ),
            "--connector-target-fixture",
            _path(
                "tests",
                "fixtures",
                "source_fact_binding_readiness",
                "synthetic_stage1_connector_semantic_target_field_matrix.v1.fixture.json",
            ),
            "--gate-report-schema",
            _path(
                "schemas",
                "source_fact_binding_readiness",
                "stage1_connector_semantic_readiness_gate_report.schema.json",
            ),
            "--gate-report-fixture",
            _path(
                "tests",
                "fixtures",
                "source_fact_binding_readiness",
                "synthetic_stage1_connector_semantic_readiness_gate_report.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "source_evidence_acceptance_consumer_contract_check.py"),
            "--repo-root",
            ".",
            "--consumer-contract-schema",
            _path(
                "src",
                "qtt",
                "source_evidence",
                "acceptance",
                "accepted_source_evidence_consumer_contract.schema.json",
            ),
            "--target-field-ledger-schema",
            _path(
                "src",
                "qtt",
                "source_evidence",
                "acceptance",
                "stage1_target_field_acceptance_ledger_record.schema.json",
            ),
            "--export-record-schema",
            _path(
                "src",
                "qtt",
                "source_evidence",
                "acceptance",
                "stage1_accepted_source_evidence_export_record.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "acceptance_consumer_contract",
                "synthetic_accepted_source_evidence_consumer_contract_records.v1.fixture.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "stage1_connector_semantic_binding_ledger_check.py"),
            "--repo-root",
            ".",
            "--ledger-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "connector_semantic_binding",
                "stage1_connector_semantic_binding_ledger_record.schema.json",
            ),
            "--canonicalization-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "connector_semantic_binding",
                "stage1_connector_semantic_value_canonicalization.schema.json",
            ),
            "--consumer-contract-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "connector_semantic_binding",
                "stage1_connector_semantic_binding_consumer_contract.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "connector_semantic_binding",
                "synthetic_stage1_connector_semantic_binding_contracts.v1.fixture.json",
            ),
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "Stage1ConnectorSemanticBindingLedgerCheck.report.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "stage1_runtime_resolver_snapshot_contract_check.py"),
            "--repo-root",
            ".",
            "--input-lock-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "runtime_resolver",
                "stage1_runtime_resolver_snapshot_input_lock.schema.json",
            ),
            "--manifest-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "runtime_resolver",
                "stage1_runtime_resolver_snapshot_manifest.schema.json",
            ),
            "--consumer-contract-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "runtime_resolver",
                "stage1_runtime_resolver_consumer_contract.schema.json",
            ),
            "--gate-report-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "runtime_resolver",
                "stage1_runtime_resolver_snapshot_gate_report.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "runtime_resolver",
                "synthetic_stage1_runtime_resolver_snapshot_contracts.v1.fixture.json",
            ),
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "Stage1RuntimeResolverSnapshotContractCheck.report.json",
            ),
        ],
        [
            sys.executable,
            _path(
                "tools",
                "stage1_runtime_resolver_to_replay_paper_handoff_check.py",
            ),
            "--repo-root",
            ".",
            "--consumer-allowlist-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "runtime_resolver_snapshot",
                "stage1_runtime_resolver_snapshot_consumer_allowlist.schema.json",
            ),
            "--handoff-contract-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "runtime_resolver_snapshot",
                "stage1_runtime_resolver_to_replay_paper_handoff_contract.schema.json",
            ),
            "--handoff-report-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "runtime_resolver_snapshot",
                "stage1_runtime_resolver_to_replay_paper_handoff_report.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "runtime_resolver_snapshot",
                "synthetic_stage1_runtime_resolver_to_replay_paper_handoff.v1.fixture.json",
            ),
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "Stage1RuntimeResolverToReplayPaperHandoff.report.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "stage1_concurrent_replay_paper_contract_check.py"),
            "--repo-root",
            ".",
            "--input-identity-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "replay_paper",
                "concurrent_replay_paper_input_identity.schema.json",
            ),
            "--replay-lane-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "replay_paper",
                "concurrent_replay_lane_contract.schema.json",
            ),
            "--paper-lane-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "replay_paper",
                "concurrent_paper_lane_contract.schema.json",
            ),
            "--replay-result-boundary-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "replay_paper",
                "replay_result_packet_boundary.schema.json",
            ),
            "--paper-result-boundary-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "replay_paper",
                "paper_result_packet_boundary.schema.json",
            ),
            "--gate-report-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "replay_paper",
                "concurrent_replay_paper_execution_gate_report.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "replay_paper",
                "synthetic_concurrent_replay_paper_contracts.v1.fixture.json",
            ),
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "Stage1ConcurrentReplayPaperContractCheck.report.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "stage1_dual_result_review_contract_check.py"),
            "--repo-root",
            ".",
            "--input-contract-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "dual_result_review",
                "stage1_dual_result_review_input_contract.schema.json",
            ),
            "--comparison-matrix-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "dual_result_review",
                "stage1_replay_paper_comparison_matrix.schema.json",
            ),
            "--gate-report-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "dual_result_review",
                "stage1_dual_result_review_gate_report.schema.json",
            ),
            "--owner-handoff-block-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "dual_result_review",
                "stage1_owner_live_promotion_handoff_block.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "dual_result_review",
                "synthetic_stage1_dual_result_review_contracts.v1.fixture.json",
            ),
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "Stage1DualResultReviewContractCheck.report.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "stage1_owner_live_promotion_review_contract_check.py"),
            "--repo-root",
            ".",
            "--input-contract-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "owner_live_promotion_review",
                "stage1_owner_live_promotion_review_input_contract.schema.json",
            ),
            "--owner-approval-receipt-boundary-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "owner_live_promotion_review",
                "stage1_owner_approval_receipt_boundary.schema.json",
            ),
            "--gate-report-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "owner_live_promotion_review",
                "stage1_owner_live_promotion_review_gate_report.schema.json",
            ),
            "--handoff-block-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "owner_live_promotion_review",
                "stage1_three_venue_canary_eligibility_handoff_block.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "owner_live_promotion_review",
                "synthetic_stage1_owner_live_promotion_review_contracts.v1.fixture.json",
            ),
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "Stage1OwnerLivePromotionReviewContractCheck.report.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "stage1_three_venue_canary_eligibility_contract_check.py"),
            "--repo-root",
            ".",
            "--input-contract-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "three_venue_canary_eligibility",
                "stage1_three_venue_canary_eligibility_input_contract.schema.json",
            ),
            "--readiness-matrix-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "three_venue_canary_eligibility",
                "stage1_three_venue_platform_readiness_matrix.schema.json",
            ),
            "--handoff-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "three_venue_canary_eligibility",
                "stage1_owner_review_to_canary_eligibility_handoff.schema.json",
            ),
            "--gate-report-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "three_venue_canary_eligibility",
                "stage1_three_venue_canary_eligibility_gate_report.schema.json",
            ),
            "--execution-block-schema",
            _path(
                "src",
                "qtt",
                "stage1_prediction_markets",
                "three_venue_canary_eligibility",
                "stage1_limited_live_canary_execution_block.schema.json",
            ),
            "--fixture",
            _path(
                "tests",
                "fixtures",
                "source_evidence",
                "three_venue_canary_eligibility",
                "synthetic_stage1_three_venue_canary_eligibility_contracts.v1.fixture.json",
            ),
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "Stage1ThreeVenueCanaryEligibilityContractCheck.report.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "build_master_plan_section_coverage_report.py"),
        ],
        [
            sys.executable,
            _path("tools", "validate_master_plan_section_coverage.py"),
            "--mode",
            "dev",
        ],
        [
            sys.executable,
            _path("tools", "qtt_test_gate.py"),
            "--phase",
            "first-coding-runbook",
            "--repo-root",
            ".",
            "--strict-no-claim",
            "--out",
            _path("docs", "master_plan", "generated", "QTTTestGate.report.json"),
        ],
        [
            sys.executable,
            _path("tools", "local_gate_command_matrix.py"),
            "--repo-root",
            ".",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "LocalGateCommandMatrix.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "pr_handoff_check.py"),
            "--repo-root",
            ".",
            "--out",
            _path(
                "docs",
                "master_plan",
                "generated",
                "FirstCodingPRHandoff.packet.json",
            ),
        ],
        [
            sys.executable,
            _path("tools", "validate_no_runtime_artifacts.py"),
            "--repo-root",
            ".",
            "--forbid-source-retrieval",
            "--forbid-source-acceptance",
            "--forbid-connector-binding",
            "--forbid-private-state-fetch",
            "--forbid-order-execution",
            "--forbid-neural-training",
            "--forbid-neural-inference",
            "--forbid-external-repo-clone",
            "--forbid-package-install-scripts",
        ],
        [
            sys.executable,
            _path("tools", "run_pytest_fresh_basetemp.py"),
            "-q",
        ],
    ]


def run_commands(commands: Sequence[Sequence[str]]) -> int:
    for command in commands:
        command_list = list(command)
        print(subprocess.list2cmdline(command_list), flush=True)
        completed = subprocess.run(command_list)
        if completed.returncode != 0:
            return completed.returncode

    print(SUCCESS_MARKER, flush=True)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else list(argv)
    if args:
        print("run_validation_gates.py does not accept arguments", file=sys.stderr)
        return 2
    with tempfile.TemporaryDirectory(prefix="qtt_validation_gates_") as temp_dir:
        return run_commands(build_validation_commands(pathlib.Path(temp_dir)))


if __name__ == "__main__":
    raise SystemExit(main())
