"""VS2 policy constants."""

from .models import AUTHORITY_BOUNDARY_REF, BLOCKER_POLICY_REF, EXECUTION_AUTHORITY_REF

__all__ = ["AUTHORITY_BOUNDARY_REF", "BLOCKER_POLICY_REF", "EXECUTION_AUTHORITY_REF"]
